### PR TITLE
Use PHP 7.1

### PR DESCRIPTION
**Pull request by darklow**

### CODE REVIEW

**Comment by darklow** [comment]
Unfortunately not every koken feature work under PHP 7.1 or 7.0.
Installation and main features work fine, but some minor doesn't.
For example you cannot delete photos on PHP 7 (just nothing happens and photo stays undeleted and Trash is still 0), while on PHP 5 it works.
Please close PR or let's wait when Koken is ready for PHP 7 and then PR can be merged.

**Comment by waredsystems** [comment]
Koken is ready for PHP7. Delete photos on PHP7 works ! You just need to install php7-xml (php-dom equivalent on PHP5)

**Comment by darklow** [comment]
@waredsystems Thanks, will try adding php7-xml and see how it goes.

**Comment by MikeCostello** [comment]
There is also the [php7](https://github.com/koken/docker-koken-lemp/tree/php7) branch
`docker build --rm -t koken/koken-lemp https://github.com/koken/docker-koken-lemp.git#php7`

**Pull request closed without merging**
